/**
 * Interactive setup — creates .env with project defaults.
 * Run: npm run setup
 */

import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(dirname(fileURLToPath(import.meta.url)), ".env");

const rl = createInterface({ input, output });

async function ask(question, fallback = "") {
  const hint = fallback ? ` [${fallback}]` : "";
  const answer = (await rl.question(`${question}${hint}: `)).trim();
  return answer || fallback;
}

async function main() {
  console.log("\nTelegram ↔ Cursor bot setup\n");

  if (existsSync(envPath)) {
    const overwrite = await ask(".env already exists. Overwrite? (y/N)", "N");
    if (overwrite.toLowerCase() !== "y") {
      console.log("Skipped.");
      rl.close();
      return;
    }
  }

  const telegramToken = await ask("TELEGRAM_BOT_TOKEN (from @BotFather)");
  const cursorApiKey = await ask("CURSOR_API_KEY (Cursor Dashboard → Integrations)");
  const allowedUserIds = await ask("Your Telegram user ID (@userinfobot)", "");
  const agentMode = await ask("Agent mode: local | cloud", "local");

  const content = `# Generated by npm run setup
TELEGRAM_BOT_TOKEN=${telegramToken}
CURSOR_API_KEY=${cursorApiKey}
ALLOWED_USER_IDS=${allowedUserIds}

AGENT_MODE=${agentMode}

WORKSPACE=${root.replace(/\\/g, "/")}

CLOUD_REPO_URL=https://github.com/daniil-themeal/themeal.git
CLOUD_REPO_REF=feature/next

CURSOR_MODEL=composer-2.5
`;

  writeFileSync(envPath, content, "utf8");
  console.log(`\nSaved ${envPath}`);
  console.log("Start the bot: npm start\n");
  rl.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
