/** Feather icon set order from Figma grid (9 columns, left-to-right, top-to-bottom). */
export const FEATHER_ICON_NAMES = [
  'Activity',
  'Airplay',
  'Alert circle',
  'Alert octagon',
  'Alert triangle',
  'Align center',
  'Align justify',
  'Align left',
  'Align right',
  'Anchor',
  'Aperture',
  'Archive',
  'Arrow down circle',
  'Arrow down-left',
  'Arrow down-right',
  'Arrow down',
  'Arrow left-circle',
  'Arrow left',
  'Arrow right-circle',
  'Arrow right',
  'Arrow up-circle',
  'Arrow up-left',
  'Arrow up-right',
  'Arrow up',
  'At sign',
  'Award',
  'Bar chart-2',
  'Bar chart',
  'Battery charging',
  'Battery',
  'Bell off',
  'Bell',
  'Bluetooth',
  'Bold',
  'Book open',
  'Book',
  'Bookmark',
  'Box',
  'Briefcase',
  'Calendar',
  'Camera off',
  'Camera',
  'Cast',
  'Check circle',
  'Check square',
  'Check',
  'Chevron down',
  'Chevron left',
  'Chevron right',
  'Chevron up',
  'Chevrons down',
  'Chevrons left',
  'Chevrons right',
  'Chevrons up',
  'Chrome',
  'Circle',
  'Clipboard',
  'Clock',
  'Cloud drizzle',
  'Cloud lightning',
  'Cloud off',
  'Cloud rain',
  'Cloud snow',
  'Cloud',
  'Code',
  'Codepen',
  'Codesandbox',
  'Coffee',
  'Columns',
  'Command',
  'Compass',
  'Copy',
  'Corner down-left',
  'Corner down-right',
  'Corner left-down',
  'Corner left-up',
  'Corner right-down',
  'Corner right-up',
  'Corner up-left',
  'Corner up-right',
  'Cpu',
  'Credit card',
  'Crop',
  'Crosshair',
  'Database',
  'Delete',
  'Disc',
  'Divide circle',
  'Divide square',
  'Divide',
  'Dollar sign',
  'Download cloud',
  'Download',
  'Dribbble',
  'Droplet',
  'Edit 2',
  'Edit 3',
  'Edit',
  'External link',
  'Eye off',
  'Eye',
  'Facebook',
  'Fast forward',
  'Feather',
  'Figma',
  'File minus',
  'File plus',
  'File text',
  'File',
  'Film',
  'Filter',
  'Flag',
  'Folder minus',
  'Folder plus',
  'Folder',
  'Framer',
  'Frown',
  'Gift',
  'Git branch',
  'Git commit',
  'Git merge',
  'Git pull-request',
  'Github',
  'Gitlab',
  'Globe',
  'Grid',
  'Hard drive',
  'Hash',
  'Headphones',
  'Heart',
  'Help circle',
  'Hexagon',
  'Home',
  'Image',
  'Inbox',
  'Info',
  'Instagram',
  'Italic',
  'Key',
  'Layers',
  'Layout',
  'Life buoy',
  'Link 2',
  'Link',
  'Linkedin',
  'List',
  'Loader',
  'Lock',
  'Log in',
  'Log out',
  'Mail',
  'Map pin',
  'Map',
  'Maximize 2',
  'Maximize',
  'Meh',
  'Menu',
  'Message circle',
  'Message square',
  'Mic off',
  'Mic',
  'Minimize 2',
  'Minimize',
  'Minus circle',
  'Minus square',
  'Minus',
  'Monitor',
  'Moon',
  'More horizontal',
  'More vertical',
  'Mouse pointer',
  'Move',
  'Music',
  'Navigation 2',
  'Navigation',
  'Octagon',
  'Package',
  'Paperclip',
  'Pause circle',
  'Pause',
  'Pen tool',
  'Percent',
  'Phone call',
  'Phone forwarded',
  'Phone incoming',
  'Phone missed',
  'Phone off',
  'Phone outgoing',
  'Phone',
  'Pie chart',
  'Play circle',
  'Play',
  'Plus circle',
  'Plus square',
  'Plus',
  'Pocket',
  'Power',
  'Printer',
  'Radio',
  'Refresh ccw',
  'Refresh cw',
  'Repeat',
  'Rewind',
  'Rotate ccw',
  'Rotate cw',
  'Rss',
  'Save',
  'Scissors',
  'Search',
  'Send',
  'Server',
  'Settings',
  'Share 2',
  'Share',
  'Shield off',
  'Shield',
  'Shopping bag',
  'Shopping cart',
  'Shuffle',
  'Sidebar',
  'Skip back',
  'Skip forward',
  'Slack',
  'Slash',
  'Sliders',
  'Smartphone',
  'Smile',
  'Speaker',
  'Square',
  'Star',
  'Stop circle',
  'Sun',
  'Sunrise',
  'Sunset',
  'Table',
  'Tablet',
  'Tag',
  'Target',
  'Terminal',
  'Thermometer',
  'Thumbs down',
  'Thumbs up',
  'Toggle left',
  'Toggle right',
  'Tool',
  'Trash 2',
  'Trash',
  'Trello',
  'Trending down',
  'Trending up',
  'Triangle',
  'Truck',
  'Tv',
  'Twitch',
  'Twitter',
  'Type',
  'Umbrella',
  'Underline',
  'Unlock',
  'Upload cloud',
  'Upload',
  'User check',
  'User minus',
  'User plus',
  'User x',
  'User',
  'Users',
  'Video off',
  'Video',
  'Voicemail',
  'Volume 1',
  'Volume 2',
  'Volume x',
  'Volume',
  'Watch',
  'Wifi off',
  'Wifi',
  'Wind',
  'X circle',
  'X octagon',
  'X square',
  'X',
  'Youtube',
  'Zap off',
  'Zap',
  'Zoom in',
  'Zoom out',
] as const;

export type FeatherIconName = (typeof FEATHER_ICON_NAMES)[number];

export const FEATHER_ICON_IMPORT_SIZES = [16, 20, 24, 32, 40, 48] as const;

export type FeatherIconImportSize = (typeof FEATHER_ICON_IMPORT_SIZES)[number];

export function featherIconNameToSlug(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, '-');
}

export function getFeatherArchiveFileName(
  index: number,
  size: FeatherIconImportSize | 12,
): string {
  return index === 0 ? `Size=${size}.svg` : `Size=${size}-${index}.svg`;
}

export const FEATHER_ICON_MANIFEST = FEATHER_ICON_NAMES.map((figmaName, index) => ({
  index,
  figmaName,
  slug: featherIconNameToSlug(figmaName),
}));

/** Indexes used by existing app icon components. */
export const APP_ICON_INDEX_BY_SLUG = {
  box: 37,
  'chevron-right': 48,
  'check-circle': 43,
  check: 45,
  'map-pin': 151,
  package: 176,
  smile: 226,
  truck: 251,
  x: 281,
} as const;
