/** Auto-generated by npm run reviews:import — do not edit manually. */
/** Source: testimonial.to embed */

export type ReviewPlatform = 'instagram' | 'twitter' | 'linkedin' | 'facebook' | 'other';

export type CustomerReview = {
  id: string;
  kind: 'text' | 'social';
  text: string;
  name: string;
  subtitle?: string;
  rating?: number;
  platform?: ReviewPlatform;
  imageUrl?: string;
  videoUrl?: string;
  avatarUrl?: string;
  socialLink?: string;
};

export const customersReviews: CustomerReview[] = [
  {
    id: "aziza-with-two-kids-under-2-t",
    kind: "social",
    text: "With two kids under 2, The Meal is just perfect for me seriously I always don't have time to cook for me but bcz of you I always eat my meal on time ..lots of prayers for you and your business..May Almighty give you more success Ameen s ameenCathrina Paula Manalo",
    name: "Aziza",
    rating: 5,
    platform: "other",
    imageUrl: "https://firebasestorage.googleapis.com/v0/b/testimonialto.appspot.com/o/testimonials%2Ffc94214d-bdad-4aa9-bfdd-ce1f44eb57f7%2Fattached?alt=media&token=b2549651-fb78-41c2-8e75-1df625cd4cc9&hasOriginal=true",
  },
  {
    id: "fatima-i-can-spend-my-quality-t",
    kind: "social",
    text: "I can spend my quality time with my kids rather than spending time cooking and thinking about what to cook. TheMeal truly made my daily life healthier, lighter, and stress-free.Viktoriya",
    name: "Fatima",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/a931f0b6-d3d1-4f6a-b43b-191fb6683e59/videoThumbnail",
  },
  {
    id: "mohammed-as-of-now-i-m-happy-with",
    kind: "social",
    text: "As of now I'm happy with the meal that is being delivered to me...it's been only a week ...each delivery is getting excited for me...looking forward for new recipe...Ahmed",
    name: "Mohammed",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/b7fd39fe-e99a-4cfb-ac04-7d9c843f1524/videoThumbnail",
  },
  {
    id: "vihaan-the-food-was-bursting-wi",
    kind: "social",
    text: "The food was bursting with flavors – perfectly balanced spices, rich textures, and fresh ingredients. Each bite likely brought something unique and memorable.the dishes were plated beautifully, making them as visually appealing as they were delicious. A thoughtful presentation can make the meal feel even more special.Fathimathul",
    name: "Vihaan",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/835d31ca-1dcf-4d37-9629-29f4e50ebfee/videoThumbnail",
  },
  {
    id: "maria-this-meal-service-has-be",
    kind: "social",
    text: "This meal service has been incredibly helpful! No need to worry about grocery shopping, cooking, or cleaning — it’s so convenient to have a freshly cooked meal every day. I don’t even need to spend on outside food, even when I’m at the office. I absolutely love it! Just a small request: if possible, please replace the beef meals in my plan and occasionally add a little extra sauce when it’s missing. Thank you — I highly recommend this service to every working professional in Dubai!Fizah",
    name: "Maria",
    subtitle: "Marketer, 36",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/eb06f45b-8d05-47f6-89b4-4e8aff068f7f/videoThumbnail",
    avatarUrl: "https://cdn.testimonial.to/testimonials/0b813f6e-659f-4af0-b09b-259898c0acdf/avatar",
  },
  {
    id: "adam-mchugh-very-impressed-by-the-me",
    kind: "social",
    text: "Very impressed by the meals offered and the price. 5/5 👍Muhannad Walid mr kunafa",
    name: "Adam McHugh",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/c11a3ac9-9e52-4339-a9be-9900917f3532/videoThumbnail",
    avatarUrl: "https://cdn.testimonial.to/testimonials/-OsXJNpn3LjcKhDolFae/e2b439b4-00f1-4918-9c99-3f6f2824fab0-avatar",
  },
  {
    id: "ahmed-quality-taste-good-helpf",
    kind: "social",
    text: "Quality Taste good Helpful customer services Said jibril",
    name: "Ahmed",
    rating: 5,
    platform: "other",
    imageUrl: "https://image.mux.com/YrFWv302Z01laeZCfNq28WDSY9RKsOur3TYeprOwm00QxU/thumbnail.jpg?width=0",
    videoUrl: "https://stream.mux.com/YrFWv302Z01laeZCfNq28WDSY9RKsOur3TYeprOwm00QxU/high.mp4",
    avatarUrl: "https://cdn.testimonial.to/testimonials/59f1c65c-a8f4-4aae-ab65-551919b89121/avatar",
  },
  {
    id: "abood-packed-very-well-all-the",
    kind: "text",
    text: "Packed very well all the details on each meal is a plus It made my day faster not thinking of cooking Its all good maybe just if the meals are cooked daily would feel better (maybe) I would somehow recommend it Bolognese",
    name: "Abood",
    rating: 5,
  },
  {
    id: "nadezhda-i-used-to-order-ready-me",
    kind: "social",
    text: "I used to order ready meals from other services — it turned out to be significantly more expensive. Here, the price is fixed, and you know you're paying for the month in advance. The food arrives in vacuum-sealed packaging and stays in the fridge for 3–4 days with no issues. I heat it up in the microwave — and it tastes as fresh as ever. I recommend it to anyone who's tired of the 'what to eat' dilemma.Janine Alyssa",
    name: "Nadezhda",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/1448868b-7700-44cd-92fe-fd332fcc71a3/videoThumbnail",
  },
  {
    id: "susana-the-most-noticeable-chan",
    kind: "social",
    text: "The most noticeable change is that I stopped spending time on grocery shopping and cooking. After work, that was the last thing I wanted to do. Now that step is just gone, and my days feel a lot easier. Haidara Ali",
    name: "Susana",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/629e3618-7edc-4ea2-a706-0a8dc0582e30/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "nadine-i-m-not-on-a-strict-diet",
    kind: "social",
    text: "I’m not on a strict diet, but I do track calories. I liked that everything is already labeled — protein, calories, etc. Sometimes I’m too lazy to calculate anything, so this makes it super easy. That’s the main benefit for me.Jinny 6 months on a meal plan in Dubai ! That’s what happened : 1. I start earning more as I leveled up my mind and don’t have to think what to eat ( what to buy and how to cook ) so I can focus on bigger ideas ! 2. I started eating more regularly, food is balanced and I don’t overeat ! 3. I save to e and money ( no cooking no endless grossery shopping) ! It’s not just a meal plan it’s like level up your lifestyle with @themeal_uae!Eslam El",
    name: "Nadine",
    rating: 5,
    platform: "instagram",
    imageUrl: "https://cdn.testimonial.to/testimonials/cdf4a740-90c4-469b-be86-826105cfa2cb/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "maria-jonas-i-don-t-have-a-stable-sc",
    kind: "text",
    text: "I don’t have a stable schedule — every day is different. Food used to always be a `secondary priority` for me. Now at least that part is sorted. I don’t have to think about what to cook or order — the food is already there. It really clears my head. I also like that I don’t have to sit around all day waiting for delivery — I just choose a convenient time, wake up, and the food is already at my door. And the price is nice too.",
    name: "Maria Jonas",
    rating: 5,
  },
  {
    id: "liz-sarceno-i-tried-different-servic",
    kind: "social",
    text: "I tried different services, but this one stood out because of its simplicity. No complicated menus, just normal, good food. Portions are solid, I get full.Jason",
    name: "Liz Sarceno",
    rating: 5,
    platform: "other",
    imageUrl: "https://image.mux.com/BXFbjaJ2DM00GpRADtxkkWjs7h87EYeM7VqpA02glAh6o/thumbnail.jpg?width=0",
    videoUrl: "https://stream.mux.com/BXFbjaJ2DM00GpRADtxkkWjs7h87EYeM7VqpA02glAh6o/high.mp4",
  },
  {
    id: "dinar-s-i-really-like-this-food",
    kind: "social",
    text: "I really like this food delivery! It really helps me control my weight and eat deliciously.Boutaina",
    name: "Dinar S",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/1e065529-6748-4f9b-b03d-11ac057f24ab/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "george-i-first-tried-it-just-fo",
    kind: "social",
    text: "I first tried it just for a couple of days, just to test it. Ended up using it for weeks. You get used to it very quickly — honestly, I don’t want to go back to cooking.Humera Khadija",
    name: "George",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/b95e5c0d-3908-4825-a0ff-e13381798106/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
    avatarUrl: "https://cdn.testimonial.to/testimonials/67d54886-eca1-4ddc-be56-ad9be8ecd2cd/avatar",
  },
  {
    id: "anam-fatima-shaikh-looking-to-simplify-your",
    kind: "social",
    text: "Looking to simplify your daily meals while enjoying delicious variety? 🍴✨ *The Meal* has you covered! With perfectly portioned meals for breakfast, lunch, and dinner delivered straight to your doorstep, they make eating healthy and convenient a breeze. Every day brings a new menu, so you’ll never get bored! Plus, their monthly package is an unbeatable deal at just 999 AED. Say goodbye to meal prep stress and hello to fresh, tasty, and hassle-free dining with *The Meal*! 💼🚪 Ahmed",
    name: "Anam Fatima Shaikh",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/cc64ede8-cbe8-494f-85fd-191e7352a04a/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "jason-food-was-delicious-ever",
    kind: "social",
    text: "Food was delicious! Every meal tasted 10/10. Since I’m in a bulking phase I do eat some snacks in between to hit my calories but great value ❤️Johnlerie",
    name: "Jason",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/87ab535b-30a4-46e0-9a33-cf65ce611a5f/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "michael-i-ve-fallen-in-love-with",
    kind: "text",
    text: "I've fallen in love with my fridge 😅😅😅 Before, it was a place I dreaded looking into — but now it's always full of delicious food that I don't have to cook.",
    name: "Michael",
    rating: 5,
  },
  {
    id: "darina-d-i-took-a-one-month-plan",
    kind: "social",
    text: "I took a one‑month plan with two meals a day — it's perfect for working in an office. I can have a relaxed breakfast at work, and in the evening I don't binge on food. A special thank you for being able to pause the plan when I'm away.Hazar",
    name: "Darina D",
    rating: 5,
    platform: "other",
    imageUrl: "https://cdn.testimonial.to/testimonials/a5e9cd35-3605-43ad-9c22-71dc88ce78f8/videoThumbnail",
    videoUrl: "https://stream.mux.com/xImFc7Ckrw1mnKSknl8u5G6rmZodRiGGoRxXTFrbpos/high.mp4",
  },
  {
    id: "farhan-i-have-become-much-more",
    kind: "text",
    text: "I have become much more consistent with my diet, and I no longer feel bored because the meals change every day. The variety you offer really helps me stay on track and move closer to my goal of losing weight along with going to the gym. Having three meals a day also stopped me from thinking about “what will I eat today,” which makes the whole process much easier for me.",
    name: "Farhan",
    rating: 5,
  },
];
